spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
#quando for a primeira vez o comando abaixo precisa ser "create" depois tudo bem alterar para validate porque a tabela jรก subiu para PROD.
      ddl-auto: validate
